title: "Claisen Docs"
description: "Personalised gut‑health guides: bloating, gas, heartburn & GERD."
url: "https://docs.claisen.com"
baseurl: ""              # no leading slash
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
